name: pre-commit

on:
    push:
        branches: [main, master, cmake_dev]
    pull_request:
        branches: [main, master, cmake_dev]

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4.1.7
        - uses: actions/setup-python@v5.1.1
          with:
            python-version: '3.10'
        - uses: pre-commit/action@v3.0.1
