name: pre-commit

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4.1.7
        - uses: actions/setup-python@v5.1.1
          with:
            python-version: '3.10'
        - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd #v3.0.1
